const VERSES_DB = [
    // --- STRENGTH & COURAGE ---
    { text: "Be strong and courageous. Do not be afraid; do not be discouraged.", ref: "Joshua 1:9" },
    { text: "I can do all things through Christ who strengthens me.", ref: "Philippians 4:13" },
    { text: "The Lord is my light and my salvation—whom shall I fear?", ref: "Psalm 27:1" },
    { text: "But those who hope in the Lord will renew their strength.", ref: "Isaiah 40:31" },
    { text: "If God is for us, who can be against us?", ref: "Romans 8:31" },
    { text: "The Lord will fight for you; you need only to be still.", ref: "Exodus 14:14" },
    { text: "Be on your guard; stand firm in the faith; be courageous; be strong.", ref: "1 Corinthians 16:13" },
    { text: "For the Spirit God gave us does not make us timid, but gives us power.", ref: "2 Timothy 1:7" },
    { text: "Wait for the Lord; be strong and take heart.", ref: "Psalm 27:14" },
    { text: "My flesh and my heart may fail, but God is the strength of my heart.", ref: "Psalm 73:26" },

    // --- PEACE & ANXIETY ---
    { text: "Cast all your anxiety on him because he cares for you.", ref: "1 Peter 5:7" },
    { text: "Peace I leave with you; my peace I give you.", ref: "John 14:27" },
    { text: "When I am afraid, I put my trust in you.", ref: "Psalm 56:3" },
    { text: "Do not let your hearts be troubled. You believe in God; believe also in me.", ref: "John 14:1" },
    { text: "Come to me, all you who are weary and burdened, and I will give you rest.", ref: "Matthew 11:28" },
    { text: "The Lord is near to all who call on him.", ref: "Psalm 145:18" },
    { text: "Be still, and know that I am God.", ref: "Psalm 46:10" },
    { text: "In peace I will lie down and sleep, for you alone, Lord, make me dwell in safety.", ref: "Psalm 4:8" },
    { text: "He leads me beside quiet waters, he refreshes my soul.", ref: "Psalm 23:2-3" },
    { text: "Do not worry about tomorrow, for tomorrow will worry about itself.", ref: "Matthew 6:34" },

    // --- LOVE & KINDNESS ---
    { text: "Love is patient, love is kind.", ref: "1 Corinthians 13:4" },
    { text: "We love because he first loved us.", ref: "1 John 4:19" },
    { text: "A friend loves at all times.", ref: "Proverbs 17:17" },
    { text: "Let all that you do be done in love.", ref: "1 Corinthians 16:14" },
    { text: "Above all, love each other deeply, because love covers over a multitude of sins.", ref: "1 Peter 4:8" },
    { text: "Greater love has no one than this: to lay down one’s life for one’s friends.", ref: "John 15:13" },
    { text: "Beloved, let us love one another, for love is from God.", ref: "1 John 4:7" },
    { text: "Hatred stirs up conflict, but love covers over all wrongs.", ref: "Proverbs 10:12" },
    { text: "And over all these virtues put on love, which binds them all together in perfect unity.", ref: "Colossians 3:14" },
    { text: "For God so loved the world that he gave his one and only Son.", ref: "John 3:16" },

    // --- WISDOM & GUIDANCE ---
    { text: "Trust in the Lord with all your heart and lean not on your own understanding.", ref: "Proverbs 3:5" },
    { text: "Your word is a lamp for my feet, a light on my path.", ref: "Psalm 119:105" },
    { text: "The fear of the Lord is the beginning of knowledge.", ref: "Proverbs 1:7" },
    { text: "Ask and it will be given to you; seek and you will find.", ref: "Matthew 7:7" },
    { text: "If any of you lacks wisdom, you should ask God.", ref: "James 1:5" },
    { text: "Commit your way to the Lord; trust in him and he will do this.", ref: "Psalm 37:5" },
    { text: "For I know the plans I have for you, plans to prosper you and not to harm you.", ref: "Jeremiah 29:11" },
    { text: "Iron sharpens iron, and one man sharpens another.", ref: "Proverbs 27:17" },
    { text: "Whatever you do, work at it with all your heart.", ref: "Colossians 3:23" },
    { text: "Walk with the wise and become wise.", ref: "Proverbs 13:20" },

    // --- SHORT & PUNCHY (Best for small banners) ---
    { text: "Jesus wept.", ref: "John 11:35" },
    { text: "Rejoice always.", ref: "1 Thessalonians 5:16" },
    { text: "Pray without ceasing.", ref: "1 Thessalonians 5:17" },
    { text: "The Lord is my shepherd.", ref: "Psalm 23:1" },
    { text: "God is love.", ref: "1 John 4:8" },
    { text: "He is risen!", ref: "Matthew 28:6" },
    { text: "Fear not, for I am with you.", ref: "Isaiah 41:10" },
    { text: "Faith moves mountains.", ref: "Matthew 17:20" },
    { text: "I am the way and the truth and the life.", ref: "John 14:6" },
    { text: "Let your light shine.", ref: "Matthew 5:16" },

    // --- PURITY & FLEEING TEMPTATION ---
    { text: "Flee from sexual immorality. Every other sin a person commits is outside the body.", ref: "1 Corinthians 6:18" },
    { text: "Flee the evil desires of youth and pursue righteousness, faith, love and peace.", ref: "2 Timothy 2:22" },
    { text: "But I tell you that anyone who looks at a woman lustfully has already committed adultery with her in his heart.", ref: "Matthew 5:28" },
    { text: "It is God’s will that you should be sanctified: that you should avoid sexual immorality.", ref: "1 Thessalonians 4:3" },
    { text: "How can a young person stay on the path of purity? By living according to your word.", ref: "Psalm 119:9" },
    { text: "Marriage should be honored by all, and the marriage bed kept pure.", ref: "Hebrews 13:4" },
    { text: "Do not lust in your heart after her beauty or let her captivate you with her eyes.", ref: "Proverbs 6:25" },
    { text: "Can a man scoop fire into his lap without his clothes being burned?", ref: "Proverbs 6:27" },
    { text: "Put to death, therefore, whatever belongs to your earthly nature: sexual immorality, impurity, lust.", ref: "Colossians 3:5" },
    { text: "I made a covenant with my eyes not to look lustfully at a young woman.", ref: "Job 31:1" },

    // --- REPROOF, DISCIPLINE & CORRECTION ---
    { text: "Whoever loves discipline loves knowledge, but whoever hates correction is stupid.", ref: "Proverbs 12:1" },
    { text: "Those whom I love I rebuke and discipline. So be earnest and repent.", ref: "Revelation 3:19" },
    { text: "Wounds from a friend can be trusted, but an enemy multiplies kisses.", ref: "Proverbs 27:6" },
    { text: "My son, do not despise the Lord’s discipline, and do not resent his rebuke.", ref: "Proverbs 3:11" },
    { text: "For the Lord disciplines the one he loves, and chastises every son whom he receives.", ref: "Hebrews 12:6" },
    { text: "A fool spurns a parent’s discipline, but whoever heeds correction shows prudence.", ref: "Proverbs 15:5" },
    { text: "Better is open rebuke than hidden love.", ref: "Proverbs 27:5" },
    { text: "He who ignores discipline comes to poverty and shame, but whoever heeds correction is honored.", ref: "Proverbs 13:18" },
    { text: "Like an earring of gold... is a wise reprover to a listening ear.", ref: "Proverbs 25:12" },
    { text: "All Scripture is God-breathed and is useful for teaching, rebuking, correcting and training.", ref: "2 Timothy 3:16" },

    // --- SELF-CONTROL & SOBRIETY ---
    { text: "Like a city whose walls are broken through is a person who lacks self-control.", ref: "Proverbs 25:28" },
    { text: "For the grace of God... teaches us to say 'No' to ungodliness and worldly passions.", ref: "Titus 2:11-12" },
    { text: "Be alert and of sober mind. Your enemy the devil prowls around like a roaring lion.", ref: "1 Peter 5:8" },
    { text: "Do not get drunk on wine, which leads to debauchery. Instead, be filled with the Spirit.", ref: "Ephesians 5:18" },
    { text: "Everything is permissible for me, but I will not be mastered by anything.", ref: "1 Corinthians 6:12" },
    { text: "Whoever is slow to anger is better than the mighty, and he who rules his spirit than he who takes a city.", ref: "Proverbs 16:32" },
    { text: "But the fruit of the Spirit is love, joy, peace... and self-control.", ref: "Galatians 5:22-23" },
    { text: "Strictly discipline your body and bring it into subjection.", ref: "1 Corinthians 9:27" },
    { text: "The end of all things is near. Therefore be alert and of sober mind so that you may pray.", ref: "1 Peter 4:7" },
    { text: "Do not conform to the pattern of this world, but be transformed by the renewing of your mind.", ref: "Romans 12:2" },

    // --- INTEGRITY & HONESTY ---
    { text: "The Lord detests lying lips, but he delights in people who are trustworthy.", ref: "Proverbs 12:22" },
    { text: "Whoever walks in integrity walks securely, but whoever takes crooked paths will be found out.", ref: "Proverbs 10:9" },
    { text: "Better is a poor man who walks in his integrity than a rich man who is crooked in his ways.", ref: "Proverbs 28:6" },
    { text: "The integrity of the upright guides them, but the unfaithful are destroyed by their duplicity.", ref: "Proverbs 11:3" },
    { text: "Whoever can be trusted with very little can also be trusted with much.", ref: "Luke 16:10" },
    { text: "Provide things honest in the sight of all men.", ref: "Romans 12:17" },
    { text: "Do not lie to each other, since you have taken off your old self with its practices.", ref: "Colossians 3:9" },
    { text: "A false balance is an abomination to the Lord, but a just weight is his delight.", ref: "Proverbs 11:1" },
    { text: "Renounce the secret and shameful ways; do not use deception.", ref: "2 Corinthians 4:2" },
    { text: "Let your 'Yes' be 'Yes,' and your 'No,' 'No'.", ref: "Matthew 5:37" },

    // --- PRIDE vs. HUMILITY ---
    { text: "God opposes the proud but shows favor to the humble.", ref: "James 4:6" },
    { text: "Pride goes before destruction, a haughty spirit before a fall.", ref: "Proverbs 16:18" },
    { text: "When pride comes, then comes disgrace, but with humility comes wisdom.", ref: "Proverbs 11:2" },
    { text: "Do nothing out of selfish ambition or vain conceit. Rather, in humility value others above yourselves.", ref: "Philippians 2:3" },
    { text: "Humble yourselves before the Lord, and he will lift you up.", ref: "James 4:10" },
    { text: "Let another praise you, and not your own mouth; a stranger, and not your own lips.", ref: "Proverbs 27:2" },
    { text: "Live in harmony with one another. Do not be proud, but be willing to associate with people of low position.", ref: "Romans 12:16" },
    { text: "Everyone who exalts himself will be humbled, and he who humbles himself will be exalted.", ref: "Luke 14:11" },
    { text: "The fear of the Lord is instruction in wisdom, and humility comes before honor.", ref: "Proverbs 15:33" },
    { text: "Do you see a man who is wise in his own eyes? There is more hope for a fool than for him.", ref: "Proverbs 26:12" },

    // --- WARNINGS ON GREED & MONEY ---
    { text: "For the love of money is a root of all kinds of evil.", ref: "1 Timothy 6:10" },
    { text: "You cannot serve both God and money.", ref: "Matthew 6:24" },
    { text: "Keep your lives free from the love of money and be content with what you have.", ref: "Hebrews 13:5" },
    { text: "What good is it for someone to gain the whole world, yet forfeit their soul?", ref: "Mark 8:36" },
    { text: "Whoever loves money never has money enough; whoever loves wealth is never satisfied with his income.", ref: "Ecclesiastes 5:10" },
    { text: "Do not store up for yourselves treasures on earth, where moths and vermin destroy.", ref: "Matthew 6:19" },
    { text: "Better is a little with the fear of the Lord than great treasure and trouble with it.", ref: "Proverbs 15:16" },
    { text: "Dishonest money dwindles away, but whoever gathers money little by little makes it grow.", ref: "Proverbs 13:11" },
    { text: "A greedy man brings trouble to his family, but he who hates bribes will live.", ref: "Proverbs 15:27" },
    { text: "Command those who are rich... not to be arrogant nor to put their hope in wealth.", ref: "1 Timothy 6:17" },

    // --- SPEECH & THE TONGUE ---
    { text: "A gentle answer turns away wrath, but a harsh word stirs up anger.", ref: "Proverbs 15:1" },
    { text: "Do not let any unwholesome talk come out of your mouths, but only what is helpful for building others up.", ref: "Ephesians 4:29" },
    { text: "Even a fool is thought wise if he keeps silent, and discerning if he holds his tongue.", ref: "Proverbs 17:28" },
    { text: "Everyone should be quick to listen, slow to speak and slow to become angry.", ref: "James 1:19" },
    { text: "Those who guard their mouths and their tongues keep themselves from calamity.", ref: "Proverbs 21:23" },
    { text: "The tongue has the power of life and death, and those who love it will eat its fruit.", ref: "Proverbs 18:21" },
    { text: "Avoid godless chatter, because those who indulge in it will become more and more ungodly.", ref: "2 Timothy 2:16" },
    { text: "If anyone thinks he is religious and does not bridle his tongue but deceives his heart, this person's religion is worthless.", ref: "James 1:26" },
    { text: "Let your conversation be always full of grace, seasoned with salt.", ref: "Colossians 4:6" },
    { text: "Set a guard over my mouth, Lord; keep watch over the door of my lips.", ref: "Psalm 141:3" }
];